#!/bin/bash

if [ "$1" == "" ]
then
	echo Invalid usage : agent_3parssh InServ
	exit 3
fi

echo "<<<3parssh>>>"
echo "---statcpu---"
ssh $2@$1 statcpu -d 1 -iter 1 -t
echo "---statcpu---"

echo "---showbattery---"
ssh $2@$1 showbattery -d
echo "---showbattery---"
